import React from 'react';
import { VerticalTimeline, VerticalTimelineElement }  from 'react-vertical-timeline-component';
import timelineElements from "./timelineElements";
import { ReactComponent as WorkIcon } from "./thuiskapper-svg.svg";
import { ReactComponent as SchoolIcon } from "./thuiskapper-svg.svg";
import './VerticalTimeline.css';
import './VerticalTimelineElement.css';


export default function Home() {
  let workIconStyles = {background: "#3cb371"};
  let schoolIconStyles = {background: "#3cb371"};

  return (

      <div >
        <div style={whitepaperStyle}>
          <h1 className="text-4xl font-bold">Whitepaper ThuisKapper Token (TKT)</h1>
          <p className="leading-10 my-12 text-2xl">ThuisKapperTokens (TKT), a new cryptocurrency created to represent and support the production and promotion of our ThuisKapper.app web- platform and iOS and Android application. Our platform is created for mobile barbers and hairdressers to seek and find clients near their location in The Netherlands.</p>
          <p className="leading-8 my-6 text-xl">This document will relay all information about the use cases of our TKT, including it’s structure, distribution, utility and timeline’s for our planned development. Overtime changes and updates will be featured in this document which is available at: <a href="https://tkt.thuiskapper.app" title="URL of this document" className="text-green-600 font-bold hover:text-green-900">https://tkt.thuiskapper.app</a>.</p>

          <h2 className="text-3xl font-bold">Platform for Barbers and Hairdressers</h2>
          <p className="leading-8 my-6 text-xl">Our platform was invented after the first wave of Covid-19 in 2020 and we launched in the last semester of 2020. It has been around 9 months since we officially launched our beta version of thuiskapper.app. We have run a test cycle with 1 barber located in Rotterdam.</p>

          <p className="leading-8 my-6 text-xl">During that cycle we experienced how easy it was for the barber to communicate with the clients through our platform. We also personally asked the clients and barbers for their opinions and if they had any suggestions to make our platform more customer friendly, which we have implanted into our platform.</p>

          <h2 className="text-3xl font-bold">An existing company, backed by a cryptocurrency</h2>
          <p className="leading-8 my-6 text-xl">Become part of our company and earn your part and share of the profits generated by our platform. Our ThuisKapper.app platform will be solo backed by individual investors who will directory own a part of the company’s liquidity through the BSC blockchain (Binance Smart Chain). All profit’s that are being generated throughout our ThuisKapper.app platform fee’s will be divided as following back into the company:</p>
          <ul className="sm:block md:flex ">
          <li className="leading-8 text-usder flex-1 p-3 text-lg bg-gray-100 sm:mb-5 md:mr-4 mb-2"><strong className="block">33% Liquidity for Promotion</strong> <span>Facebook, Google Ads, Reviews and much more!</span></li>
          <li className="leading-8 text-usder flex-1 p-3 text-lg bg-gray-100 sm:mb-5 md:mr-2 md:ml-2 mb-2"><strong className="block">33% Liquidity for Infrastructure</strong> <span>Computers for automation, staff and other expenses needed to run the company.</span></li>
          <li className="leading-8 text-usder flex-1 p-3 text-lg bg-gray-100 sm:mb-5 md:ml-4 mb-2"><strong className="block">34% Liquidity for Tokenboost</strong><span>We will purchase tokens back every month to boost liquidity and price.</span></li>
          </ul>
          <p className="leading-8 my-6 text-xl">Eventually the Paid promotion and workers / infrastructure liquidity perusdages may differ from original. The 34% Liquidity that we will add into to the pool will stay forever until we are at the moon!</p>

          <h3 className="text-3xl font-bold">Paid Promotions</h3>
          <p className="leading-8 my-6 text-xl">For paid promotions we will be using social media platforms as: Instagram, Facebook and Google Adwords. We currently having good results and our Adwords promotions and are looking forward to extend our promo’s to the Facebook and Instagram marketplaces.</p>

          <h3 className="text-3xl font-bold">Workers and infrastructure</h3>
          <p className="leading-8 my-6 text-xl">Personal can’t work for free unfortunately, but lucky as we are Python does work for free but only costs us a little bit of electricity and time to program to our desires. To increase the visits of our platform we want to build multiple web- data scrapers to contact barbers and hairdressers to start working for us as we can easy find the clientell.</p>

          <p className="leading-8 my-6 text-xl">One example is a Dutch online open market place: www.marktplaats.nl, where mobile barbers create advertisements for their services on location. We can build Python automation bots that will automatically contact (New) barbers or mobile hairdressers through WhatsApp when their WhatsApp phone number has not been found yet in our database.</p>
          <p className="leading-8 my-6 text-xl">We want to create a certain amount of automatization tools in order to keep the platform running 24/7 without actually someone have to work, besides customer support. A lot of python tools take a lot of RAM and good infrastructure of devices and security which require funds  and time to be created and to keep the computers running.</p>


          <h2 className="text-3xl font-bold">TKT Liquidity Pool</h2>
          <ul className="mb-12 w-full my-4 mb-10 relative">
          <li className="w-full leading-8 w-full bg-gray-100 p-8  m-auto text-usder"><strong className="text-usder text-lg">TKT Contract Adres (BSC Scan): </strong><span className="block sm:text-sm md:text-lg">0x8a8d90d6b15cb15a5921884bec1c5bb9bfbf22f1</span></li>
          </ul>

          <h2 className="text-3xl font-bold">Token Distribution</h2>
            <p className="leading-8 my-6 text-xl">Initial pre-sale will be valued at 0,08$ per TKT and there will be a limited supply available where the price will be increasing over time based on the amount sold. After the presale we will provide the liquidity and will slowly bring the rest of the TKT to the market in late 2022.</p>
            <p className="leading-8 my-6 text-xl">Tokens which will not be sold through our pre-sale will be used for future expansion of our company to different countries. When we have more information about expansion we will update our white paper to clarify our business progress.</p>


        <h2 className="text-3xl font-bold">Token Cap / Pricing</h2>
        <strong>Current cap: 9600 - 100K (0,08$ e.a.)</strong>
        <p className="leading-8 my-6 text-xl">
            <div className="flex mb-1">
            <div className="flex-1">- 0 - 100K</div>              <div className="flex-1">-> 0,08 usd each.</div>
            </div><div className="flex mb-1">
            <div className="flex-1">- 100k - 200K</div>        <div className="flex-1">-> 0,10 usd each.</div>
            </div><div className="flex mb-1">
            <div className="flex-1">- 200k - 300K</div>       <div className="flex-1">-> 0,12 usd each.</div>
            </div><div className="flex mb-1">
            <div className="flex-1">- 300k - 500K</div>        <div className="flex-1">-> 0,14 usd each.</div>
            </div><div className="flex mb-1">
            <div className="flex-1">- 500k - 1M</div>           <div className="flex-1">-> 0,19 usd each.</div>
            </div><div className="flex mb-1">
            <div className="flex-1">- 1M - 2M</div>                <div className="flex-1">-> 0,22 usd each.</div>
            </div><div className="flex mb-1">
            <div className="flex-1">- 2M - 5M</div>                <div className="flex-1">-> 0,25 usd each.</div>
            </div><div className="flex mb-1">
            <div className="flex-1">- 5M - 10M</div>              <div className="flex-1">-> 0,30 usd each.</div>
            </div><div className="flex mb-1">
            <div className="flex-1">- 10M - 20M</div>           <div className="flex-1">-> 0,35 usd each.</div>
            </div><div className="flex mb-1">
            <div className="flex-1">- 20M - 30M</div>             <div className="flex-1">-> 0,42 usd each.</div></div></p>


        <h2 className="text-3xl font-bold">Project Development</h2>
        <div className=" bg-gray-100 padding-10">
          <VerticalTimeline className="my-10">
            {timelineElements.map(element => {

                let isWorkIcon = element.icon === "work";
              return (
                <VerticalTimelineElement
                  key={element.key}
                  date={element.date}
                  dateClassName="date text-gray-600"
                  iconStyle={isWorkIcon ? workIconStyles : schoolIconStyles}
                  icon={isWorkIcon ? <WorkIcon /> : <SchoolIcon />}
                >
                  <h3 className="vertical-timeline-element-title font-bold">
                    {element.title}
                  </h3>
                  <h5 className="vertical-timeline-element-subtitle">
                    {element.location}
                  </h5>
                  <p id="description">{element.description}</p>
                </VerticalTimelineElement>
              )
            })}
          </VerticalTimeline>
        </div>
          <h2 className="text-3xl font-bold">Definations</h2>
          <p className="leading-8 my-6 text-xl">DAO (Decentralized Autonomous Organization) means that the organization represented by a series of smart contracts publishing on the BSC (Binance Smart Chain). Which, when launched will be eventually controlled by the users of the ThuisKapper Platform.</p><br />
          <ul className="my-6 ">
          <li className="mb-6"><span className="leading-8 my-6 text-xl"><strong>“ThuisKapper”</strong> in this meaning stands for “ThuisKapper.app”, a commonwealth of Purmerend corporation.</span></li>
          <li className="mb-6"><span className="leading-8 my-6 text-xl"><strong>“ThuisKapper Platform”</strong> means the platform and applications which are published through Desktop or Mobile devices, aswell as on the Apple AppStore and Google Play.</span></li>
          <li className="mb-6"><span className="leading-8 my-6 text-xl"><strong>“User” </strong>references to any individual and or entity using the ThuisKapper platform or Web3 application.</span></li>
</ul>
          <h2 className="text-3xl font-bold">Legal Disclaimer</h2>

          <p className="leading-8 my-6 text-xl">This Whitepaper is for all general information purposes about our ThuisKapper.app Project. It does not include financial advise or recommendations or any form of solicitation. For all information published over time, ThuisKapper.app remains the right to update the information provided by our company.</p>
          <p className="leading-8 my-6 text-xl">ThuisKapper created the TKT token to reward barbers and users that will using our platform. We also have the idea of adding a webshop to our platform in the near future where our barbers and other web- based clients will be able to purchase their tools and items, using TKT. Barbers will be able to earn rewards according to their weekly, monthly and yearly points they have generated when cutting clients at home. We have made the decision to start using web3 based dApps because the security protocol of the blockchain lies so much higher than a usdralized MySQL database for storing passwords and user sensitive data. No TKT token will represent any economic interest in ThuisKapper at any time, and ThuisKapper developed TKT for the purpose of use within the ThuisKapper Platform.</p>
          <p className="leading-8 my-6 text-xl">Through the development of the TKT, ThuisKapper does not grant any rights, express, or implied other than the right to use TKT on our ThuisKapper Platform or within the DAO. We deny any ability of the TKT token to be represented or conferred any ownership right, share, security or equivalent rights. We also deny the right to receive future revenue shares, or any other form of participation in / or related to ThuisKapper or our ThuisKapper Platform and any of its corporate affiliates.
          ThuisKapper reserves the right to fully reject the usage of TKT tokens on the ThuisKapper Platform. ThuisKapper will be not be responsible for any direct or consequential loss or damage from any kind arising directly or indirectly from: (1) Applicable to any information provided, (2) Any miscommunication, error, inaccuracy or any such information; or - any action resulting from such information.</p>
          <p className="leading-8 my-6 text-xl">To fully extend permitted by applicable law and except otherwise when specified in writing by ThuisKapper:</p>
          <p className="leading-8 my-6 text-xl">(1) TKT tokens are provided on an “as available” or “as is” basis without warranty of any kind. Our thuisKapper disclaimer is about all implied warranties as the TKT tokens, including and without limitation or implied warranties of merchantability. (2) ThuisKapper does not represent or warrant the TKT tokens that are reliable, current, error-free, or that technical defects in TKT tokens will be corrected.</p>
          <p className="leading-8 my-6 text-xl">In this Whitepaper, there will be no terms that constitute a prospectus, offer document of any kind or are intended to constitute an offer of securities or solicitation for investment in securities. When you have received your TKT tokens, please not that our ThuisKapper Platform contributes and / or participating do not represent, or constitute or involve the values created or formed by exchanges. This could be due to any form of security, investment units and form of ordinary project shares, in any platform.</p>
          <p className="leading-8 my-6 text-xl">TKT Whitepaper in any part, or copy there for must not be transmitted to any country where distribution or dissemination of these documents and relevant information is restricted or prohibited. No regulated authority has examined or approved this, until today about the information set in this white paper. Publication, distribution and dissemination of these terms do not imply that applicable laws, regulatory requirements or rules have complied with it.</p>
          <p className="leading-8 my-6 text-xl">To examine this document to the fullest permitted by applicable laws, regulations and rules, ThuisKapper and our ThuisKapper Platform, it’s founder’s, team, users and barbers or any other third party will not be involved in our project and shall not be liable for any direct or indirect loss of any kind. Not in contracts or otherwise loss of revenue, income or profits and loss of use or data. Every user or barber that will use the ThuisKapper platform will automatically be in acceptance of the information provided by our Whitepaper, visitable by the link provided in the first part of this document.</p>
          <p className="leading-8 my-6 text-xl">All statements in our Whitepaper, ThuisKapper Platform or other Thuiskapper relative pages made in press releases or in any place accessible by the public, that may be made by ThuisKapper, it’s founders, team or any other third party involved in ThuisKapper Platform, are not statements of historical facts constituting “Forward-looking statements”. Information provided in this white paper should not be consider to be business, legal, financial advise or contribution or participation to the development of the ThuisKapper network or any of it’s related projects. ThuisKapper does not intend to make disclaims or any representation, warranty or undertaking of any form whatsoever to any entity or person. This includes any representation or warranty / undertaking in relation to the truth, accuracy and completeness of the information publishing in our TKT Whitepaper.</p>
          <p className="leading-8 my-6 text-xl">All ThuisKapper token holders are responsible for implementing reasonable measures for security of their own wallet, vault or other related storing mechanism used for holding ThuisKapper tokens, including the requisite private key(s) or other credentials necessary to acces their wallet or storing mechanism. When private key’s or other credentials are lost, the holder might lose the access to their TKT tokens, therefor we are not responsible in the case of users not storing their data safely. We will not have not obligations in any form to you in favor of our ThuisKapper tokens. ThuisKapper is not responsible for lose, cost, or expenses in relation to lost access credentials. The token holder holds the responsibility to withhold, collect, send, transfer or secure his own TKT and remit the correct taxes to the appropriate tax authorities regarding any received ThuisKapperTokens (TKT).</p>
          <p className="leading-8 my-6 text-xl">Prior to the DAO launch our ThuisKapper token and ThuisKapper platform will maintain the control over the protocol. Upon the launch of our DAO, ThuisKapper will no longer maintain any control of the price and any financial fluctuations of whatsoever. ThuisKapper expressly denies all responsibility for any transactions occurred though the BSC (Binance Smart Chain) or any other third party. ThuisKapper maintains the sole discretion to launch the SPS token on a different blockchain, without requiring to launch on the BSC or any blockchain whatsoever.</p>
        </div>
      </div>

  )
}

const whitepaperStyle = {
  background: 'white'
}
