import React from 'react';

export default function Home() {
  return (

      <div >
        <div style={whitepaperStyle}>
          <h1>Whitepaper ThuisKapperToken (TKT)</h1>
          <p>ThuisKapperTokens (TKT), a new cryptocurrency created to represent and support the production and promotion of our ThuisKapper.app web- platform and iOS and Android application. Our platform is created for mobile barbers and hairdressers to seek and find clients near their location in The Netherlands.</p>

          <p>This document will relay all information about the use cases of our TKT, including it’s structure, distribution, utility and timeline’s for our planned development. Overtime changes and updates will be featured in this document which is available at: https://tkt.thuiskapper.app.</p>

          <h2>Platform for Barbers and Hairdressers</h2>
          <p>Our platform was invented after the first wave of Covid-19 in 2020 and we launched in the last semester of 2020. It has been around 9 months since we officially launched our beta version of thuiskapper.app. We have run a test cycle with 1 barber located in Rotterdam.</p>

          <p>During that cycle we experienced how easy it was for the barber to communicate with the clients through our platform. We also personally asked the clients and barbers for their opinions and if they had any suggestions to make our platform more customer friendly, which we have implanted into our platform.</p>

          <h2>An existing company, backed by a cryptocurrency</h2>
          <p>Become part of our company and earn your part and share of the profits generated by our platform. Our ThuisKapper.app platform will be solo backed by individual investors who will directory own a part of the company’s liquidity through the BSC blockchain (Binance Smart Chain). All profit’s that are being generated throughout our ThuisKapper.app platform fee’s will be divided as following back into the company:</p>
          <ul>
          <li>33% Liquidity will be used for: paid promotion like social ads and Adwords for example. They will be spend directly back into growth of the company.</li>
          <li>33% Liquidity will be used for: workers and infrastructure within the company such as: devices to automate certain processes with Python.</li>
          <li>34% Liquidity will constantly be added in our own TKT liquidity pool to increase the value of TKT.</li>
          </ul>
          <p>Eventually the Paid promotion and workers / infrastructure liquidity percentages may differ from original. The 34% Liquidity that we will add into to the pool will stay forever until we are at the moon!</p>

          <h3>Paid Promotions</h3>
          <p>For paid promotions we will be using social media platforms as: Instagram, Facebook and Google Adwords. We currently having good results and our Adwords promotions and are looking forward to extend our promo’s to the Facebook and Instagram marketplaces.</p>

          <h3>Workers and infrastructure</h3>
          <p>Personal can’t work for free unfortunately, but lucky as we are Python does work for free but only costs us a little bit of electricity and time to program to our desires. To increase the visits of our platform we want to build multiple web- data scrapers to contact barbers and hairdressers to start working for us as we can easy find the clientell.</p>

          <p>One example is a Dutch online open market place: www.marktplaats.nl, where mobile barbers create advertisements for their services on location. We can build Python automation bots that will automatically contact (New) barbers or mobile hairdressers through WhatsApp when their WhatsApp phone number has not been found yet in our database.</p>
          <p>We want to create a certain amount of automatization tools in order to keep the platform running 24/7 without actually someone have to work, besides customer support. A lot of python tools take a lot of RAM and good infrastructure of devices and security which require funds  and time to be created and to keep the computers running.</p>


          <h2>TKT Liquidity Pool</h2>
          <ul>
          <li><strong>TKT Contract Adres (BSC Scan): 0x8a8d90d6b15cb15a5921884bec1c5bb9bfbf22f1</strong></li>
          </ul>

          <h2>Token Distribution</h2>
          <p>Initial Pre-Sale will be valued at 0,08$ per TKT and there will be a limited supply available through the pre-sale which will be 2,000,000 TKT tokens. After the presale we will provide the liquidity and will slowly bring 8,000,000 TKT to the market in late 2021 / 2022.</p>
          <p>We will keep 20,000,000 tokens aside each kept on different adreses (10M e/a) for future extension to other country’s and development purposes. When we have more information about expansion we will update our white paper to clarify our business progress.</p>
          <h2>Project Development</h2>
          <p>Information following a.s.a.p.</p>
          <h2>Legal Disclaimer</h2>
<h3>DEFINITIONS</h3>
<p>DAO (Decentralized Autonomous Organization) means that the organization represented by a series of smart contracts publishing on the BSC (Binance Smart Chain). Which, when launched will be eventually controlled by the users of the ThuisKapper Platform.</p><br />

<strong>“ThuisKapper” in this meaning stands for “ThuisKapper.app”, a commonwealth of Purmerend corporation.</strong><br />
<strong>“ThuisKapper Platform” means the platform and applications which are published through Desktop or Mobile devices, aswell as on the Apple AppStore and Google Play.</strong><br />
<strong>“User” references to any individual and or entity using the ThuisKapper platform or Web3 application.</strong><br /><br />
<h3>LEGAL DISCLAIMER</h3>

<p>This Whitepaper is for all general information purposes about our ThuisKapper.app Project. It does not include financial advise or recommendations or any form of solicitation. For all information published over time, ThuisKapper.app remains the right to update the information provided by our company.</p>
<p>ThuisKapper created the TKT token to reward barbers and users that will using our platform. We also have the idea of adding a webshop to our platform in the near future where our barbers and other web- based clients will be able to purchase their tools and items, using TKT. Barbers will be able to earn rewards according to their weekly, monthly and yearly points they have generated when cutting clients at home. We have made the decision to start using web3 based dApps because the security protocol of the blockchain lies so much higher than a centralized MySQL database for storing passwords and user sensitive data. No TKT token will represent any economic interest in ThuisKapper at any time, and ThuisKapper developed TKT for the purpose of use within the ThuisKapper Platform.</p>
<p>Through the development of the TKT, ThuisKapper does not grant any rights, express, or implied other than the right to use TKT on our ThuisKapper Platform or within the DAO. We deny any ability of the TKT token to be represented or conferred any ownership right, share, security or equivalent rights. We also deny the right to receive future revenue shares, or any other form of participation in / or related to ThuisKapper or our ThuisKapper Platform and any of its corporate affiliates.
ThuisKapper reserves the right to fully reject the usage of TKT tokens on the ThuisKapper Platform. ThuisKapper will be not be responsible for any direct or consequential loss or damage from any kind arising directly or indirectly from: (1) Applicable to any information provided, (2) Any miscommunication, error, inaccuracy or any such information; or - any action resulting from such information.</p>
<p>To fully extend permitted by applicable law and except otherwise when specified in writing by ThuisKapper:</p>
<p>(1) TKT tokens are provided on an “as available” or “as is” basis without warranty of any kind. Our thuisKapper disclaimer is about all implied warranties as the TKT tokens, including and without limitation or implied warranties of merchantability. (2) ThuisKapper does not represent or warrant the TKT tokens that are reliable, current, error-free, or that technical defects in TKT tokens will be corrected.</p>
<p>In this Whitepaper, there will be no terms that constitute a prospectus, offer document of any kind or are intended to constitute an offer of securities or solicitation for investment in securities. When you have received your TKT tokens, please not that our ThuisKapper Platform contributes and / or participating do not represent, or constitute or involve the values created or formed by exchanges. This could be due to any form of security, investment units and form of ordinary project shares, in any platform.</p>
<p>TKT Whitepaper in any part, or copy there for must not be transmitted to any country where distribution or dissemination of these documents and relevant information is restricted or prohibited. No regulated authority has examined or approved this, until today about the information set in this white paper. Publication, distribution and dissemination of these terms do not imply that applicable laws, regulatory requirements or rules have complied with it.</p>
<p>To examine this document to the fullest permitted by applicable laws, regulations and rules, ThuisKapper and our ThuisKapper Platform, it’s founder’s, team, users and barbers or any other third party will not be involved in our project and shall not be liable for any direct or indirect loss of any kind. Not in contracts or otherwise loss of revenue, income or profits and loss of use or data. Every user or barber that will use the ThuisKapper platform will automatically be in acceptance of the information provided by our Whitepaper, visitable by the link provided in the first part of this document.</p>
<p>All statements in our Whitepaper, ThuisKapper Platform or other Thuiskapper relative pages made in press releases or in any place accessible by the public, that may be made by ThuisKapper, it’s founders, team or any other third party involved in ThuisKapper Platform, are not statements of historical facts constituting “Forward-looking statements”. Information provided in this white paper should not be consider to be business, legal, financial advise or contribution or participation to the development of the ThuisKapper network or any of it’s related projects. ThuisKapper does not intend to make disclaims or any representation, warranty or undertaking of any form whatsoever to any entity or person. This includes any representation or warranty / undertaking in relation to the truth, accuracy and completeness of the information publishing in our TKT Whitepaper.</p>
<p>All ThuisKapper token holders are responsible for implementing reasonable measures for security of their own wallet, vault or other related storing mechanism used for holding ThuisKapper tokens, including the requisite private key(s) or other credentials necessary to acces their wallet or storing mechanism. When private key’s or other credentials are lost, the holder might lose the access to their TKT tokens, therefor we are not responsible in the case of users not storing their data safely. We will not have not obligations in any form to you in favor of our ThuisKapper tokens. ThuisKapper is not responsible for lose, cost, or expenses in relation to lost access credentials. The token holder holds the responsibility to withhold, collect, send, transfer or secure his own TKT and remit the correct taxes to the appropriate tax authorities regarding any received ThuisKapperTokens (TKT).</p>
<p>Prior to the DAO launch our ThuisKapper token and ThuisKapper platform will maintain the control over the protocol. Upon the launch of our DAO, ThuisKapper will no longer maintain any control of the price and any financial fluctuations of whatsoever. ThuisKapper expressly denies all responsibility for any transactions occurred though the BSC (Binance Smart Chain) or any other third party. ThuisKapper maintains the sole discretion to launch the SPS token on a different blockchain, without requiring to launch on the BSC or any blockchain whatsoever.</p>
      </div>
      </div>

  )
}

const whitepaperStyle = {
  background: 'white'
}
